time;level;logger;message;callsite;exception
2020-11-27 21:21:14.2810;Error;Facelift_App.Repositories.PalletRepository;The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.;Facelift_App.Repositories.PalletRepository.UpdateManualAsync;"System.InvalidOperationException: The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.ValidateContextsAreCompatible(RelatedEnd targetRelatedEnd)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.Add(IEntityWrapper wrappedTarget, Boolean applyConstraints, Boolean addRelationshipAsUnchanged, Boolean relationshipAlreadyExists, Boolean allowModifyingOtherEndOfRelationship, Boolean forceForeignKeyChanges)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IEntityWrapper wrappedOwner, RelatedEnd relatedEnd, IEntityWrapper entityToAdd, Boolean isForeignKeyChange)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.Linq.InternalSet`1.<FindInternalAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Facelift_App.Repositories.PalletRepository.<UpdateManualAsync>d__28.MoveNext() in C:\Users\Muhammad Bhovdair\Documents\Kretayuga\Projects\Unilever\UNILEVER_Facelift\Facelift_App\Repositories\PalletRepository.cs:line 741"
2020-11-27 21:21:36.4621;Error;Facelift_App.Repositories.PalletRepository;The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.;Facelift_App.Repositories.PalletRepository.UpdateManualAsync;"System.InvalidOperationException: The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.ValidateContextsAreCompatible(RelatedEnd targetRelatedEnd)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.Add(IEntityWrapper wrappedTarget, Boolean applyConstraints, Boolean addRelationshipAsUnchanged, Boolean relationshipAlreadyExists, Boolean allowModifyingOtherEndOfRelationship, Boolean forceForeignKeyChanges)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IEntityWrapper wrappedOwner, RelatedEnd relatedEnd, IEntityWrapper entityToAdd, Boolean isForeignKeyChange)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.Linq.InternalSet`1.<FindInternalAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Facelift_App.Repositories.PalletRepository.<UpdateManualAsync>d__28.MoveNext() in C:\Users\Muhammad Bhovdair\Documents\Kretayuga\Projects\Unilever\UNILEVER_Facelift\Facelift_App\Repositories\PalletRepository.cs:line 741"
2020-11-27 21:22:04.0592;Error;Facelift_App.Repositories.PalletRepository;The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.;Facelift_App.Repositories.PalletRepository.UpdateManualAsync;"System.InvalidOperationException: The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.ValidateContextsAreCompatible(RelatedEnd targetRelatedEnd)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.Add(IEntityWrapper wrappedTarget, Boolean applyConstraints, Boolean addRelationshipAsUnchanged, Boolean relationshipAlreadyExists, Boolean allowModifyingOtherEndOfRelationship, Boolean forceForeignKeyChanges)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IEntityWrapper wrappedOwner, RelatedEnd relatedEnd, IEntityWrapper entityToAdd, Boolean isForeignKeyChange)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.Linq.InternalSet`1.<FindInternalAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Facelift_App.Repositories.PalletRepository.<UpdateManualAsync>d__28.MoveNext() in C:\Users\Muhammad Bhovdair\Documents\Kretayuga\Projects\Unilever\UNILEVER_Facelift\Facelift_App\Repositories\PalletRepository.cs:line 741"
2020-11-27 21:23:34.2663;Error;Facelift_App.Repositories.PalletRepository;The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.;Facelift_App.Repositories.PalletRepository.UpdateManualAsync;"System.InvalidOperationException: The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.ValidateContextsAreCompatible(RelatedEnd targetRelatedEnd)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.Add(IEntityWrapper wrappedTarget, Boolean applyConstraints, Boolean addRelationshipAsUnchanged, Boolean relationshipAlreadyExists, Boolean allowModifyingOtherEndOfRelationship, Boolean forceForeignKeyChanges)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IEntityWrapper wrappedOwner, RelatedEnd relatedEnd, IEntityWrapper entityToAdd, Boolean isForeignKeyChange)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.Linq.InternalSet`1.<FindInternalAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Facelift_App.Repositories.PalletRepository.<UpdateManualAsync>d__28.MoveNext() in C:\Users\Muhammad Bhovdair\Documents\Kretayuga\Projects\Unilever\UNILEVER_Facelift\Facelift_App\Repositories\PalletRepository.cs:line 741"
2020-11-27 21:24:22.3338;Error;Facelift_App.Repositories.PalletRepository;The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.;Facelift_App.Repositories.PalletRepository.UpdateManualAsync;"System.InvalidOperationException: The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.ValidateContextsAreCompatible(RelatedEnd targetRelatedEnd)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.Add(IEntityWrapper wrappedTarget, Boolean applyConstraints, Boolean addRelationshipAsUnchanged, Boolean relationshipAlreadyExists, Boolean allowModifyingOtherEndOfRelationship, Boolean forceForeignKeyChanges)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IEntityWrapper wrappedOwner, RelatedEnd relatedEnd, IEntityWrapper entityToAdd, Boolean isForeignKeyChange)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.Linq.InternalSet`1.<FindInternalAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Facelift_App.Repositories.PalletRepository.<UpdateManualAsync>d__28.MoveNext() in C:\Users\Muhammad Bhovdair\Documents\Kretayuga\Projects\Unilever\UNILEVER_Facelift\Facelift_App\Repositories\PalletRepository.cs:line 741"
2020-11-27 21:25:25.6169;Error;Facelift_App.Repositories.PalletRepository;The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.;Facelift_App.Repositories.PalletRepository.UpdateManualAsync;"System.InvalidOperationException: The relationship between the two objects cannot be defined because they are attached to different ObjectContext objects.
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.ValidateContextsAreCompatible(RelatedEnd targetRelatedEnd)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.Add(IEntityWrapper wrappedTarget, Boolean applyConstraints, Boolean addRelationshipAsUnchanged, Boolean relationshipAlreadyExists, Boolean allowModifyingOtherEndOfRelationship, Boolean forceForeignKeyChanges)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IEntityWrapper wrappedOwner, RelatedEnd relatedEnd, IEntityWrapper entityToAdd, Boolean isForeignKeyChange)
   at System.Data.Entity.Core.Objects.ObjectStateManager.PerformAdd(IList`1 entries)
   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.Linq.InternalSet`1.<FindInternalAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Facelift_App.Repositories.PalletRepository.<UpdateManualAsync>d__28.MoveNext() in C:\Users\Muhammad Bhovdair\Documents\Kretayuga\Projects\Unilever\UNILEVER_Facelift\Facelift_App\Repositories\PalletRepository.cs:line 741"
